### ISSUE TITLE
您好 有提供非QQ的聯繫方式嗎？

### ISSUE THREAD

**Issue by cftang0827** [357078706/dewu#1]
您好 我們對於這個 API 接口服務相當感興趣，無奈沒有QQ帳號，想詢問是否有其他的聯繫方式(email, wechat ..etc)？謝謝

**Comment by dawenxi7475** [comment]
> 您好 我們對於這個 API 接口服務相當感興趣，無奈沒有QQ帳號，想詢問是否有其他的聯繫方式(email, wechat ..etc)？謝謝

我们团队也有提供API接口服务，可以联系asd919227259@gmail.com，谢谢。

**Comment by kaheihong** [comment]
请问怎么联系
